FROM ubuntu:22.04

RUN apt-get update \
    && apt-get install -y software-properties-common

RUN add-apt-repository ppa:deadsnakes/ppa -y \
    && apt-get update

RUN apt-get install -y python3.10 \
    && apt-get install -y python3-pip

RUN pip install fastapi uvicorn SQLAlchemy pydantic mysql-connector-python

CMD ["bash"]